groups:
  - name: example
    rules:
      # General instance down alert
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

      # cAdvisor alerts
      - alert: HighContainerCPUUsage
        expr: (sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, name) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage in container {{ $labels.name }}"
          description: "Container {{ $labels.name }} is using more than 80% CPU."

      - alert: HighContainerMemoryUsage
        expr: (sum(container_memory_usage_bytes{name!=""}) BY (instance, name)) > 2000000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage in container {{ $labels.name }}"
          description: "Container {{ $labels.name }} is using more than 2GB of memory."

      # PostgreSQL alerts
      - alert: HighPostgresConnections
        expr: pg_stat_activity_count{state="active"} > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of active PostgreSQL connections on {{ $labels.instance }}"
          description: "PostgreSQL instance {{ $labels.instance }} has more than 100 active connections."

      # Django alerts
      - alert: High5xxResponses
        expr: rate(django_http_responses_total_by_status_total{job="django", status=~"5.."}[5m]) > 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High number of 5xx responses from Django server"
          description: "The Django server is returning a high number of 5xx responses."

      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{job="django"}[5m])) by (le)) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High request latency from Django server"
          description: "The Django server is experiencing high request latency."

      # Redis alerts
      - alert: RedisMemoryUsageHigh
        expr: redis_memory_used_bytes{instance="redis-exporter:9121"} > 1073741824
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Redis memory usage is above 1 GB"
          description: "Redis instance ({{ $labels.instance }}) is using {{ $value | humanize1024 }} of memory, which is more than 1 GB."
